### ISSUE TITLE
Provide rendering of PRs

### ISSUE THREAD

**Issue by enolfc** [EGI-Federation/documentation#173]
# Short Description of the issue

It would be nice to have some rendering of the proposed PRs so people can take a look how the changes will look on the server before merging. 

# Summary of proposed changes

**Comment by gwarf** [comment]
One way to do this could be to adapt the release workflow, to deploy the update to a github pages with a baseURL containing a path segment corresponding to the PR number.
See baseURL at https://gohugo.io/getting-started/configuration/.
Then all links will have to be managed via `relURL`:  https://gohugo.io/functions/relurl/

**Comment by martaguti** [comment]
Hi @enolfc ,

This can be done nicely with the GitHub CLI https://cli.github.com 
You can checkout pr and run them locally 
gh pr list 
eg. 
gh pr checkout 284 --recurse-submodules

Then:
hugo server -D   (or the one from binaries distributed with the repo)

ps: Instructions at the end of the page at:
https://docs.egi.eu/about/contributing/git/

**Comment by gwarf** [comment]
The intent there is to be able to publish this somewhere so that less technical/in a hurry people can look directly at the rendering without having to do it locally.
It seems that if we want to do this it shouldn't be automatic (for security reason as anyone can make a PR), but it could be done for some specific Pull Requests that are marked with a specific label (as long as label cannot be set by random people opening a PR).
